### ISSUE TITLE
[Frontend]: Make the app responsive

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone-Frontend#34]
Make the client-side responsive as it is not now.

One more thing I would like to state is that while working on it, keep in mind the component wise SCSS styling and to maintain that as closely as possible.

**Comment by daacode** [comment]
Can I work on this

**Comment by Mayank0255** [comment]
@daacode 

Go ahead!!

Tag me here, incase of any doubts or queries

**Comment by Mayank0255** [comment]
Hey @daacode 

How is the work going? Stuck anywhere?

**Comment by Mayank0255** [comment]
@daacode Any updates on the progress?

**Comment by Amoghtech** [comment]
Hey is this issue still active?

**Comment by Mayank0255** [comment]
@Amoghtech yes it definitely is, wanna work on it?

**Comment by Amoghtech** [comment]
Yes I will be obliged if you assign it to me

**Comment by Mayank0255** [comment]
Cool, I will just assign it to you and I hope to get a good contribution and an active contributor added to this project👍👍

Let me know if you have any queries

**Comment by Amoghtech** [comment]
> Cool, I will just assign it to you and I hope to get a good contribution and an active contributor added to this project👍👍
> 
> Let me know if you have any queries

Yeah, will surely make a good contribution

**Comment by Amoghtech** [comment]
Hey @Mayank0255 , Can i have deployed version of this app? because after running Server, I'm getting some errors and I don't have to do backend work for now

**Comment by Mayank0255** [comment]
@Amoghtech 
So, there isn't any deployed version as if I do that then it can bring up some copyright issues.

Can you send me the server issues you are getting? I can help you fix those.
Or else give me sometime I will work on the setup in 1-2 days.
Probably the setup issues are coming up as I haven't really updated the modules for quite sometime

**Comment by Mayank0255** [comment]
@Amoghtech I have removed what was causing the error at the moment. Can you pull again and try again the setup?

And, to run the client side, you will need to run the backend server too, so that the API get's activated.

I will be implementing eslint properly by myself in a few days

**Comment by Amoghtech** [comment]
> @Amoghtech I have removed what was causing the error at the moment. Can you pull again and try again the setup?
> 
> And, to run the client side, you will need to run the backend server too, so that the API get's activated.
> 
> I will be implementing eslint properly by myself in a few days

Thanks a lot, Sorry I was busy with something else that's why I'm replying late

**Comment by Mayank0255** [comment]
@Amoghtech  Not an issue, by the why there's been an update in the codebase, front-end and backend repos have been separated and new step guidelines have been imposed, kindly follow that and you are good to go

**Comment by Amoghtech** [comment]
> @Amoghtech Not an issue, by the why there's been an update in the codebase, front-end and backend repos have been separated and new step guidelines have been imposed, kindly follow that and you are good to go

Ohkk thanks

**Comment by Mayank0255** [comment]
@Amoghtech may I ask that according to you, after how much time should I expect a PR on this?

**Comment by Amoghtech** [comment]
I will make a PR within few days as my exams were going on

**Comment by Mayank0255** [comment]
> I will make a PR within few days as my exams were going on

Cool, looking forward to it

**Comment by Mayank0255** [comment]
@Amoghtech Any updates on the PR?

**Comment by Mayank0255** [comment]
@Amoghtech kindly get back to us with a response as the fest has begun and there are some other people asking to work on this issue as well.

Pls try to get back to us by the end of the day

**Comment by AkshatMishra01** [comment]
Hey, @Mayank0255 can I work on this issue?

**Comment by Mayank0255** [comment]
@AkshatMishra01 sure you can, just wanted to ask one thing before assigning it to you that after how many days can I expect a PR? As previously also some people were ready to work on this but didn't make a PR throughout.

**Comment by AkshatMishra01** [comment]
> @AkshatMishra01 sure you can, just wanted to ask one thing before assigning it to you that after how many days can I expect a PR? As previously also some people were ready to work on this but didn't make a PR throughout.

@Mayank0255  I'll create a PR in 5 days

**Comment by Mayank0255** [comment]
@AkshatMishra01 you are most welcome then!! All the best and let me know if you get stuck anywhere.

You can contact me here or on my discord Shadowsaver#9665

I am assigning it to you 🎉

**Comment by AkshatMishra01** [comment]
@Mayank0255  i just wanted to ask which part of the source folder you want me to edit

**Comment by AkshatMishra01** [comment]
ok

**Comment by AkshatMishra01** [comment]
@Mayank0255  Dude, i'm sorry, i'm not able to do this one, please unassign me this project

**Comment by Mayank0255** [comment]
@AkshatMishra01 will you be able to do this or not? As I got a mail stating that just now, but now that comment is not been shown here. So, kindly clarify

**Comment by AkshatMishra01** [comment]
@Mayank0255  I won't be able to do this project, plz unassign me

**Comment by SaiSridhar783** [comment]
Yes @Mayank0255 , you will get a PR within a week
