### ISSUE TITLE
[Proposal]: Hosting the website

### ISSUE THREAD

**Issue by Spandan16** [Mayank0255/Stackoverflow-Clone-Frontend#54]
## Proposal

Could you host/deploy the code in a basic site hosted like vercel/heroku/firebase?

I would like to assign this work to @mrvishalsharma

**Comment by Mayank0255** [comment]
Hi @Spandan16, 
Thanks for the proposal.

Actually the thing is that this is the long term goal for now as there are two major hindrances in deploying the API and the Website.

1. For this I will have to host the MySQL database on cloud, which is not that easy as hosting a MongoDB database on cloud. And some MySQL services are even paid as well.

2. This one the biggest hindrance that is to be tackled, to deploy the backend api, there are many code conflicts, and those are all related to the MySQL code, as I have followed a pretty basic MySQL architecture, but in well structured code ORMs are used with MySQL and the connection is also established with the database in a certain manner which is been followed upto some extent right now.

To fix the ORM thing, an issue is currently active https://github.com/Mayank0255/Stackoverflow-Clone-Backend/issues/2

The ORM I am preferring to use is [Sequelize](https://sequelize.org/), the other option is to use [Prisma](https://www.prisma.io/).


Let me know if you have any queries or suggestions to tackle this, as deploying the project will be very beneficial.

**Comment by mrvishalsharma** [comment]
can you assing me this task i can work on this issue

**Comment by Spandan16** [comment]
Sure, will do that.
