### ISSUE TITLE
[Frontend]: Add Some Basic Validations For Better UX

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone-Frontend#87]
1. Max length limit for Tag Name while creation: 25 Characters
2. All Tag Names Should Be In English, So Translate it or don't allow it
3. Users Per Page Should Be 15, not 16
4. Validate the language users are inputting, dont allow any abuses or curses

**Comment by ozair-dev** [comment]
I'll try to do it.

**Comment by Mayank0255** [comment]
@ozair-dev 
Ya sure, go ahead. Looking forward to it

Btw, how much time do you think it might take you for this? There is no hurry just wanted to know an estimate

**Comment by ozair-dev** [comment]
I think I'll finish it within next 24 hrs hopefully.

**Comment by Mayank0255** [comment]
Cool, Good Luck!

**Comment by ozair-dev** [comment]
Hi,
I did a little digging and working and found out that some validations are already applied on the backend for **post title** and **post body** input fields, e.g, title should be minimum 15 characters etc.

I would'hv suggested that tags should also be validate on the backend so the frontend code would be less messier.
But as you have quoted
> Add Some Basic Validations For Better UX

So I applied some validation on **form submit**. If there are errors, it will prevent the post from actually **getting posted**.
![Screenshot from 2022-07-04 03-28-29](https://user-images.githubusercontent.com/65649182/177059326-64cf212b-a569-46a3-b0c6-4221d4d0828b.png)
![Screenshot from 2022-07-04 03-18-23](https://user-images.githubusercontent.com/65649182/177059328-ff7402db-e0cc-44c1-9ad5-932eb89923a9.png)
![Screenshot from 2022-07-04 03-17-50](https://user-images.githubusercontent.com/65649182/177059329-fb539e8f-e884-487b-9915-ec2c41253e89.png)

How do you feel about it?

**Comment by ozair-dev** [comment]
And I also set 15 users per page. I am assuming you want to see perfectly squared out grid of users, but you should note that after setting 15 users per page!

## On normal screen zoom level (100 %), I see two columns for users like this
![Screenshot from 2022-07-04 03-15-16](https://user-images.githubusercontent.com/65649182/177059408-a37df907-4744-4a38-8966-8e35f31e5a42.png)


## And at 90% zoom level, this
![Screenshot from 2022-07-04 03-15-44](https://user-images.githubusercontent.com/65649182/177059405-38286cb2-d1c8-4455-89e4-b7975576dc2d.png)

So I guess different users are gonna see different amount of grid columns

**Comment by ozair-dev** [comment]
And to deal with the inappropriate words, I can make a function like **cleanAbusiveWords(formData)**  which will traverse through the object and clean the inappropriate words before posting
e.g,

```
cleanAbusiveWrods({
    body: "This is bullshi*"
})
```
>  {
    body: "This is ********"
}

**Comment by Mayank0255** [comment]
> And I also set 15 users per page. I am assuming you want to see perfectly squared out grid of users, but you should note that after setting 15 users per page!
> 
> ## On normal screen zoom level (100 %), I see two columns for users like this
> ![Screenshot from 2022-07-04 03-15-16](https://user-images.githubusercontent.com/65649182/177059408-a37df907-4744-4a38-8966-8e35f31e5a42.png)
> 
> ## And at 90% zoom level, this
> ![Screenshot from 2022-07-04 03-15-44](https://user-images.githubusercontent.com/65649182/177059405-38286cb2-d1c8-4455-89e4-b7975576dc2d.png)
> 
> ## And on your README.md screenshots, I also see 3 grid columns
> So I guess different users are gonna see different amount of grid columns

Can you make it dynamic based on media queries?
so that it aligns on both the screen sizes

**Comment by ozair-dev** [comment]
Actually you don't need to worry about it. The users grid columns already change dynamically.
But If we set the **users count to 18**, then we can avoid this empty area when two columns are shown because we will have even number of users.

![WhatsApp Image 2022-07-06 at 12 58 46 AM](https://user-images.githubusercontent.com/65649182/177406421-337d688e-eab3-4b3f-b6ff-134a7d9e4523.jpeg)

Is it okay if I set users count to 18 instead of 15?

**Comment by Mayank0255** [comment]
@ozair-dev I think you didn't get it,

I am saying to change the count to 16 if it's two columns, and 15 if it's 3 column

**Comment by ozair-dev** [comment]
@Mayank0255 sorry, but I think you didn't get my point.

The thing is that **two or three columns** are **viewpoint** related thing, they change based on screen size, and **users count is a fixed number** and fetched once only from database, it is unnecessary to change users count based on the number of columns. But I was suggesting that we set users count to 18 because 18 is multiple of both 2 and 3, so we won't get empty space in the grid because no matter what the number of columns is, users are gonna occupy the whole space and we will get nice squared Grid of users.
Do you get it now?

**Comment by Mayank0255** [comment]
@ozair-dev 
Ya I got this point before also, we are not pagination from backend, from backend we are retrieving all the data and then paginating in the frontend. So based on viewpoint there must be a way to manipulate the limit constant.

Still it's fine, go ahead with 18 users
