### ISSUE TITLE
[Frontend]: Redesign The Top Questions Page

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone-Frontend#88]
It should look similar to this

![image](https://user-images.githubusercontent.com/43780137/176961849-c5c77301-c6ee-4af2-8f08-508a1ff2f197.png)

**Comment by BurhanRaja** [comment]
Can I help you with this?

**Comment by Mayank0255** [comment]
@BurhanRaja Ya sure, go ahead. Should I assign it to you?

**Comment by BurhanRaja** [comment]
Yes, but I am new to open source and collaborating with other people, so sorry in advance if I do anything wrong.

**Comment by BurhanRaja** [comment]
I will do my best.

**Comment by Mayank0255** [comment]
@BurhanRaja 
Ya, that is ok, as anyways I will be reviewing the PR before merging it.

Assigning you, btw how much time do you think it will take you? (No pressure, just want to have an idea)

**Comment by BurhanRaja** [comment]
Yes, I will try submitting this in 2 to 3 days. 
Do I also need to write the logic for the actions or just update the HTML and CSS part.

Currently it is looking something like this. I have updated some HTML and CSS. Am I going in the right direction?

![Screenshot (44)](https://user-images.githubusercontent.com/76507095/177038006-23a1f35a-8f2f-46a3-8df5-0637b23c8981.png)

**Comment by Mayank0255** [comment]
@BurhanRaja 

Okay, so among the filters, Interesting, Bountied and Hot wont be possible because the data that we have currently, so you dont need to add those.

In the filters, you can add 4 types, Today, Week, Month, and Year. You will need to implement that too.

The logic would be that first you be sorting based on date range, (Like if week is selected then you would get results of this week and then sort by top)
Reference to how I have applied filters and sorting in Questions Page: https://github.com/Mayank0255/Stackoverflow-Clone-Frontend/blob/53b64c37981c618802547cd17483525532de83f0/src/pages/QuestionsPage/QuestionsPage.component.jsx#L79

And in HomePage, the description of the question won't be shown, but in QuestionsPage & SingleTagPage the description should also show, rest of the design will remain the same,

The answers block should look like this if there is an answer,
![image](https://user-images.githubusercontent.com/43780137/177042520-a9b2dd48-2be7-4f10-840e-7270123f2c58.png)

**Comment by ozair-dev** [comment]
> In the filters, you can add 4 types, Today, Week, Month, and Year. You will need to implement that too.

I will let Burhan do the Job.  But if at any point, he faces any difficulty! I am here to help.

**Comment by Mayank0255** [comment]
Ya definitely

**Comment by BurhanRaja** [comment]
> @BurhanRaja
> 
> Okay, so among the filters, Interesting, Bountied and Hot wont be possible because the data that we have currently, so you dont need to add those.
> 
> In the filters, you can add 4 types, Today, Week, Month, and Year. You will need to implement that too.
> 
> The logic would be that first you be sorting based on date range, (Like if week is selected then you would get results of this week and then sort by top) Reference to how I have applied filters and sorting in Questions Page:
> 
> https://github.com/Mayank0255/Stackoverflow-Clone-Frontend/blob/53b64c37981c618802547cd17483525532de83f0/src/pages/QuestionsPage/QuestionsPage.component.jsx#L79
> 
> And in HomePage, the description of the question won't be shown, but in QuestionsPage & SingleTagPage the description should also show, rest of the design will remain the same,
> 
> The answers block should look like this if there is an answer, ![image](https://user-images.githubusercontent.com/43780137/177042520-a9b2dd48-2be7-4f10-840e-7270123f2c58.png)

Ok, I got it.

**Comment by BurhanRaja** [comment]
I am doing the filtering of Today and Month. It is showing me in console but not handling it on the website.

![Screenshot (45)](https://user-images.githubusercontent.com/76507095/177145296-e24a362b-2afe-4552-9802-2ae77d0bab4a.png)
![Screenshot (46)](https://user-images.githubusercontent.com/76507095/177145309-06c31355-21b3-4233-8a48-288c47296819.png)

This is the function I am using but not able to return it on the website.
![Screenshot (48)](https://user-images.githubusercontent.com/76507095/177145462-676a0ca7-0ece-4968-97a4-12df5c2d640e.png)

.

**Comment by BurhanRaja** [comment]
I figured out the above part but now another one of bug is coming that I am not able to switch again to the previous filter. For example if I filtered for 'Year' then I am not able to go back to 'Today'
